set BUILD_HSAILASM=1
set BUILD_LIBBRIGDWARF=1
set LLVM_PATH=E:\p4\workspaces\opencl_stg\drivers\opencl\compiler\llvm
set LLVM_SUPPORT_LIB_DIR=%LLVM_PATH%\lib\Support
set ELFTOOLCHAIN_PATH=E:\p4\workspaces\opencl_stg\drivers\hsa\contrib\elftoolchain
set LIBELF_PATH=%ELFTOOLCHAIN_PATH%\libelf
set LIBDWARF_PATH=E:\p4\workspaces\opencl_stg\drivers\sc\HSAIL\hsail-tools\libdwarf
set RE2C_EXECUTABLE=E:\p4\dk\win\re2c\re2c.exe

md build\win32
cd build\win32
set BUILD_SUBDIR=build\w8\B_dbg
cmake -G "Visual Studio 11 2012"       -DBUILD_HSAILASM=%BUILD_HSAILASM% -DBUILD_LIBBRIGDWARF=%BUILD_LIBBRIGDWARF% -DLLVM_PATH=%LLVM_PATH% -DLLVM_SUPPORT_LIB=%LLVM_SUPPORT_LIB_DIR%\%BUILD_SUBDIR%\LLVMSupport.lib "-DLIBELF_INCLUDE_DIRS=%LIBELF_PATH%;%LIBELF_PATH%/../common;%LIBELF_PATH%/../common/win32" -DLIBDWARF_INCLUDE_DIRS=%LIBDWARF_PATH%\src -DLIBELF_LIBRARIES=%LIBELF_PATH%\%BUILD_SUBDIR%\libelf.lib -DLIBDWARF_LIBRARIES=%LIBDWARF_PATH%\%BUILD_SUBDIR%\libdwarf.lib -DRE2C_EXECUTABLE=%RE2C_EXECUTABLE% %* ..\..
cd ..\..

md build\win64
cd build\win64
set BUILD_SUBDIR=build\w864a\B_dbg
cmake -G "Visual Studio 11 2012 Win64" -DBUILD_HSAILASM=%BUILD_HSAILASM% -DBUILD_LIBBRIGDWARF=%BUILD_LIBBRIGDWARF% -DLLVM_PATH=%LLVM_PATH% -DLLVM_SUPPORT_LIB=%LLVM_SUPPORT_LIB_DIR%\%BUILD_SUBDIR%\LLVMSupport.lib "-DLIBELF_INCLUDE_DIRS=%LIBELF_PATH%;%LIBELF_PATH%/../common;%LIBELF_PATH%/../common/win32" -DLIBDWARF_INCLUDE_DIRS=%LIBDWARF_PATH%\src -DLIBELF_LIBRARIES=%LIBELF_PATH%\%BUILD_SUBDIR%\libelf.lib -DLIBDWARF_LIBRARIES=%LIBDWARF_PATH%\%BUILD_SUBDIR%\libdwarf.lib -DRE2C_EXECUTABLE=%RE2C_EXECUTABLE% %* ..\..
cd ..\..
