set BUILD_HSAILASM=1
set BUILD_LIBBRIGDWARF=1
set LLVM_PATH=C:\ws\sc\drivers\opencl\compiler\llvm
set LLVM_SUPPORT_LIB_DIR=%LLVM_PATH%\lib\Support
set ELFTOOLCHAIN_PATH=C:\ws\sc\drivers\hsa\contrib\elftoolchain
set LIBELF_PATH=%ELFTOOLCHAIN_PATH%\libelf
set LIBDWARF_PATH=C:\ws\sc\drivers\sc\HSAIL\hsail-tools\libBRIGdwarf\libdwarf

md build\win32
cd build\win32
set BUILD_SUBDIR=build\w8\B_dbg
cmake -G "Visual Studio 11 2012" -DBUILD_HSAILASM=%BUILD_HSAILASM% -DBUILD_LIBBRIGDWARF=%BUILD_LIBBRIGDWARF% -DLLVM_PATH=%LLVM_PATH% -DLLVM_SUPPORT_LIB_DIR=%LLVM_SUPPORT_LIB_DIR%\%BUILD_SUBDIR% -DELFTOOLCHAIN_PATH=%ELFTOOLCHAIN_PATH% -DLIBELF_PATH=%LIBELF_PATH% -DLIBDWARF_PATH=%LIBDWARF_PATH% -DLIBELF_LIB_PATH=%LIBELF_PATH%\%BUILD_SUBDIR% -DLIBDWARF_LIB_PATH=%LIBDWARF_PATH%\%BUILD_SUBDIR% %* ..\..
cd ..\..
md build\win64
cd build\win64
set BUILD_SUBDIR=build\w864a\B_dbg
cmake -G "Visual Studio 11 2012 Win64" -DBUILD_HSAILASM=%BUILD_HSAILASM% -DBUILD_LIBBRIGDWARF=%BUILD_LIBBRIGDWARF% -DLLVM_PATH=%LLVM_PATH% -DLLVM_SUPPORT_LIB_DIR=%LLVM_SUPPORT_LIB_DIR%\%BUILD_SUBDIR% -DELFTOOLCHAIN_PATH=%ELFTOOLCHAIN_PATH% -DLIBELF_PATH=%LIBELF_PATH% -DLIBDWARF_PATH=%LIBDWARF_PATH% -DLIBELF_LIB_PATH=%LIBELF_PATH%\%BUILD_SUBDIR% -DLIBDWARF_LIB_PATH=%LIBDWARF_PATH%\%BUILD_SUBDIR% %* ..\..
cd ..\..
