#!/bin/bash

set -e
export BUILD_HSAILASM=1
export BUILD_LIBBRIGDWARF=1
export LLVM_PATH=/srv/hsa/drivers/opencl/compiler/llvm
export LLVM_SUPPORT_LIB_DIR=$LLVM_PATH/lib/Support
export ELFTOOLCHAIN_PATH=/srv/hsa/drivers/hsa/contrib/elftoolchain
export LIBELF_PATH=$ELFTOOLCHAIN_PATH/libelf
export LIBDWARF_PATH=/srv/hsa/drivers/sc/HSAIL/hsail-tools/libBRIGdwarf/libdwarf

mkdir -p build/lnx32
cd build/lnx32
export BUILD_SUBDIR=build/lnx/B_dbg
export EXTRA_CFLAGS=-m32
cmake -G "Unix Makefiles" -DBUILD_HSAILASM=$BUILD_HSAILASM -DBUILD_LIBBRIGDWARF=$BUILD_LIBBRIGDWARF -DLLVM_PATH=$LLVM_PATH -DLLVM_SUPPORT_LIB_DIR=$LLVM_SUPPORT_LIB_DIR/$BUILD_SUBDIR -DELFTOOLCHAIN_PATH=$ELFTOOLCHAIN_PATH -DLIBELF_PATH=$LIBELF_PATH -DLIBDWARF_PATH=$LIBDWARF_PATH -DLIBELF_LIB_PATH=$LIBELF_PATH/$BUILD_SUBDIR -DLIBDWARF_LIB_PATH=$LIBDWARF_PATH/$BUILD_SUBDIR -DEXTRA_CFLAGS=$EXTRA_CFLAGS "$@" ../..
cd ../..
mkdir -p build/lnx64
cd build/lnx64
export BUILD_SUBDIR=build/lnx64a/B_dbg
export EXTRA_CFLAGS=-m64
cmake -G "Unix Makefiles" -DBUILD_HSAILASM=$BUILD_HSAILASM -DBUILD_LIBBRIGDWARF=$BUILD_LIBBRIGDWARF -DLLVM_PATH=$LLVM_PATH -DLLVM_SUPPORT_LIB_DIR=$LLVM_SUPPORT_LIB_DIR/$BUILD_SUBDIR -DELFTOOLCHAIN_PATH=$ELFTOOLCHAIN_PATH -DLIBELF_PATH=$LIBELF_PATH -DLIBDWARF_PATH=$LIBDWARF_PATH -DLIBELF_LIB_PATH=$LIBELF_PATH/$BUILD_SUBDIR -DLIBDWARF_LIB_PATH=$LIBDWARF_PATH/$BUILD_SUBDIR -DEXTRA_CFLAGS=$EXTRA_CFLAGS "$@" ../..
cd ../..
