export PATH:=c:\Users\rju\p4sw\dk\win\bin;c:\Users\rju\p4sw\dk\win\gnu\cw1.3.12\bin;c:/Users/rju/p4sw/dk/win\perl\5.12.2\bin;c:\Program Files (x86)\RSA SecurID Token Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Perforce;C:\Program Files (x86)\Enterprise Vault\EVClient\;C:\Program Files (x86)\Perforce 
export LIB:=#=\# 
export LIBPATH:=#=\# 
export INCLUDE:=#=\# 
