
#include "HSAILTestGenPropDesc.h"
#include "HSAILValidatorBase.h"

#include "HSAILItems.h"
#include "Brig.h"

//==============================================================================
//==============================================================================
//==============================================================================
// Description of test properties (autogenerated)

#define PROPDESC
#include "HSAILTestGen_gen.hpp"
#undef PROPDESC

using HSAIL_ASM::PropDescImpl;

//==============================================================================
//==============================================================================
//==============================================================================

namespace TESTGEN {

static PropDescImpl* impl = 0;

void PropDesc::init(unsigned model)  { impl = new PropDescImpl(model); } 
void PropDesc::clean()               { delete impl; impl = 0; } 

      bool      PropDesc::isBrigProp(unsigned propId)                                 { return PropDescImpl::isBrigProp(propId); }
const unsigned* PropDesc::getPropVals(unsigned propId, unsigned& num)                 { return PropDescImpl::getPropVals(propId, num); }
const unsigned* PropDesc::getOpcodes(unsigned& num)                                   { return PropDescImpl::getOpcodes(num); }
const unsigned* PropDesc::getProps(unsigned opcode, unsigned& prm, unsigned& sec)     { return PropDescImpl::getProps(opcode, prm, sec); }
const unsigned* PropDesc::getPropVals(unsigned opcode, unsigned propId, unsigned& num){ return PropDescImpl::getPropVals(opcode, propId, num); }
      unsigned  PropDesc::getFormat(unsigned opcode)                                  { return PropDescImpl::getFormat(opcode); }
      bool      PropDesc::isValidProp(Inst inst, unsigned propId)                     { assert(impl); return impl->isValidProp(inst, propId); }
      bool      PropDesc::validatePrimaryProps(Inst inst)                             { assert(impl); return impl->validatePrimaryProps(inst); }
      bool      PropDesc::isValidInst(Inst inst)                                      { assert(impl); return impl->isValidInst(inst); }

}; // namespace TESTGEN

//==============================================================================
//==============================================================================
//==============================================================================


