//==============================================================================
// This file describes mappings of HDL properties to C++ constants
// These constants are used by autogenerated code
//==============================================================================

#ifndef INCLUDED_HSAIL_INST_PROPS_H
#define INCLUDED_HSAIL_INST_PROPS_H

namespace HSAIL_PROPS 
{

//==============================================================================
// Ids of properties defined in HDL

enum 
{
    PROP_MINID = 0,
    PROP_NONE  = 0,

    // Brig properties

    PROP_OPCODE, // FIXME: do we really need this property?

    PROP_TYPE,
    PROP_STYPE,
    PROP_ITYPE,
    PROP_CTYPE,

    PROP_PACKING,
    PROP_OPERATOR,
    PROP_ROUNDING,
    PROP_FTZ,
    PROP_ALIGN,
    PROP_ATMOP,
    PROP_MEMORD,
    PROP_MEMSCP,
    PROP_MEMFNC,
    PROP_GEOM,
    PROP_SEGMENT,
    PROP_WIDTH,
    PROP_EQCLASS,

    // Non-Brig properties

    PROP_TYPESIZE,
    PROP_STYPESIZE,

    PROP_D0,
    PROP_D1,

    PROP_S0,
    PROP_S1,
    PROP_S2,
    PROP_S3,
    PROP_S4,

    PROP_OPERAND, // FIXME: SHOULD WE REMOVE IT?

    PROP_MAXID
};

//==============================================================================
// Ids of property attributes

enum
{
    ATTR_MINID = 0, 

    OPERAND_ATTR_NONE,
    OPERAND_ATTR_CTYPE,
    OPERAND_ATTR_STYPE,
    OPERAND_ATTR_MODEL,
    OPERAND_ATTR_EXP,
    OPERAND_ATTR_SEXP,
    OPERAND_ATTR_NOEXP,

    EQCLASS_ATTR_NONE,

    TYPESIZE_ATTR_NONE,
    STYPESIZE_ATTR_NONE,

    ATTR_MAXID
};

//==============================================================================
// Ids of property values 

enum
{
    VAL_MINID = 0, 

    OPERAND_VAL_NULL,

    OPERAND_VAL_REG,
    OPERAND_VAL_REG_V2,
    OPERAND_VAL_REG_V3,
    OPERAND_VAL_REG_V4,

    OPERAND_VAL_IMM,
    OPERAND_VAL_LAB,
    OPERAND_VAL_ADDR_SEG,
    OPERAND_VAL_ADDR_TSEG,
    OPERAND_VAL_FUNC,
    OPERAND_VAL_ARGLIST,
    OPERAND_VAL_JUMPTAB,
    OPERAND_VAL_CALLTAB,
    OPERAND_VAL_FBARRIER,

    OPERAND_VAL_ROIMAGE,
    OPERAND_VAL_RWIMAGE,
    OPERAND_VAL_SAMPLER,
        
    OPERAND_VAL_REG_1,
    OPERAND_VAL_REG_64,
    OPERAND_VAL_REG_32,
    OPERAND_VAL_REG_128,

    OPERAND_VAL_IMM_1,
    OPERAND_VAL_IMM_32,
    OPERAND_VAL_IMM_64,
    OPERAND_VAL_IMM_128,

    OPERAND_VAL_IMM_0_1_2,
    OPERAND_VAL_IMM_0_1_2_3,

    OPERAND_VAL_REG_V2_1,
    OPERAND_VAL_REG_V2_32,
    OPERAND_VAL_REG_V2_64,
    OPERAND_VAL_REG_V2_128,

    OPERAND_VAL_REG_V3_1,
    OPERAND_VAL_REG_V3_32,
    OPERAND_VAL_REG_V3_64,
    OPERAND_VAL_REG_V3_128,

    OPERAND_VAL_REG_V4_1,
    OPERAND_VAL_REG_V4_32,
    OPERAND_VAL_REG_V4_64,
    OPERAND_VAL_REG_V4_128,

    OPERAND_VAL_INVALID,

    TYPESIZE_VAL_ATOMIC,
    TYPESIZE_VAL_MODEL,
    TYPESIZE_VAL_SEG,
    TYPESIZE_VAL_INVALID,

    STYPESIZE_VAL_MODEL   = TYPESIZE_VAL_MODEL,
    STYPESIZE_VAL_SEG     = TYPESIZE_VAL_SEG,
    STYPESIZE_VAL_INVALID = TYPESIZE_VAL_INVALID,

    EQCLASS_VAL_ANY,
    EQCLASS_VAL_INVALID,

    VAL_MAXID 
};

//==============================================================================

};

#endif // INCLUDED_HSAIL_INST_PROPS_H

